### ISSUE TITLE
last-modified date

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#10]
@jasonash I think we'll need a last-modified date/timestamp field in order to perform a sync. What do you think?

**Comment by jasonash** [comment]
Sure, I can do that. In what format would you like it?

**Comment by jessica-azgs** [comment]
Just a datestamp string, like you get with Date.now(). Not sure what you mean

**Comment by jasonash** [comment]
So are you going to populate this string, or do you want me to? That's 
my confusion. If you want to add a field, you can just add it to the 
properties list and it will be there.

**Comment by jessica-azgs** [comment]
Yes, the client will have to populate the field, true, but it should probably be a required field so that the server will reject the spot if it doesn't have this field since it is essential to synchronization.

**Comment by jessica-azgs** [comment]
@jasonash I added a field called "modified_timestamp" which will be added/updated every time spot is saved client side. It's just `new Date().getTime();` How easy/realistic would it be for the server to look at this field on update feature and if the modified_timestamp is newer on the server, keep that and send that json back in the response but if it is newer in the post request, keep the post data instead.

**Comment by jasonash** [comment]
@jessica-azgs  This shouldn't be too difficult. I'll get this going ASAP.

**Comment by jasonash** [comment]
@jessica-azgs OK, the "modified_timestamp" functionality detailed above is now working via the API. Please give it a try.
