### ISSUE TITLE
Upload photos/files for a spot

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#11]
@jasonash The camera feature has been integrated into the app so pictures can be taken and added to spots. How should this data get sent to (and retrieved from) the db?

**Comment by jasonash** [comment]
Are there going to be multiple pictures per spot?

If not, we could add functionality to the API to accept a multi-part 
form POST on http://strabospot.org/db/pictures/12345 to upload the image 
and a GET request on the same URI to request said image.

**Comment by jessica-azgs** [comment]
@zmichels should answer that but I think the answer is yes, there can be the possibility of multiple pictures per spot.

**Comment by zmichels** [comment]
yes. Multiple pictures should be able to be associated with a spot.

**Comment by jasonash** [comment]
OK, I will implement the functionality below, but will incorporate a 
separate unique identifier for pictures allowing multiple pictures per spot.

**Comment by jasonash** [comment]
There is now a service via the API for uploading pictures to the database.

There is more information about the new services here:

http://strabospot.org/api#imageFunctions

Please note that this service requires a multipart/form-data 
encapsulation with POST variables named "feature_id" and "image_file"

To help with testing, I have implemented a test page for uploading 
images to the service:

http://strabospot.org/imageupload

**Comment by jessica-azgs** [comment]
@jasonash I tried out the test page and got the error `Error: "Feature 14344875967903408 not found."` but that id is a valid id for a spot in the server db.

**Comment by jasonash** [comment]
@jessica-azgs OK, this should be fixed now. There was a lingering error in looking for the id.

**Comment by jessica-azgs** [comment]
@jasonash If a spot which has an image associated with it is uploaded and then say, the next day the spot is uploaded again it looks like on the server you then get a 2 of the same image associated with the spot. Can the server just see if the image_file being uploaded for a spot is the same as one already in the spot and then not duplicate the image?

**Comment by jasonash** [comment]
@jessica-azgs OK, this should be fixed now. I found an error which was causing images to not be deleted when a spot is deleted. Now, when the spot is deleted, all associated images are also deleted making room for the next round of uploads.

**Comment by jasonash** [comment]
@jessica-azgs OK, the image upload controller now checks to see if an image already exists for a spot with the supplied filename. If it does, an error is given. Otherwise, the image is uploaded as normal.

**Comment by jessica-azgs** [comment]
@jasonash If I add a caption to an image that was previously uploaded and then upload I'm getting a message that the image already exists on the server and the caption is not updated.

**Comment by jasonash** [comment]
@jessica-azgs OK, this should be fixed now. Now if the image already exists, it is deleted and repopulated with the new caption.

**Comment by jessica-azgs** [comment]
@jasonash Is there another way to check if the image already exists than by the file name, like just checking if the image file itself is the same? Every image we're upload has the same name of "image.jpeg" because that's not a property we're actually using in the app.

**Comment by jasonash** [comment]
@jessica-azgs I think the only way to check if the image files the same would be to compare the SHA-1 hash of each. I could conceivably calculate the hash on upload and store it in the database, and then compare on subsequent uploads for an identical hash value. I'll work on this first thing tomorrow morning.

**Comment by jasonash** [comment]
@jessica-azgs OK, I have altered the image controller to use SHA1 hashes for file comparison rather than file name. This should allow you to use the same file name for every image but still prevent duplicate images from being stored in the database.

**Comment by jessica-azgs** [comment]
@jasonash Thanks! Looks like it is working now.
