### ISSUE TITLE
new account creation error

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-server#12]
http://strabospot.org/register

Warning: Require $dbuser and $dbpassword to connect to a database server in /var/www/ez_sql_postgresql.php on line 84 Warning: Require $dbuser and $dbpassword to connect to a database server in /var/www/ez_sql_postgresql.php on line 84 Warning: pg_query(): No PostgreSQL link opened yet in /var/www/ez_sql_postgresql.php on line 220 Warning: pg_fetch_row() expects parameter 1 to be resource, boolean given in /var/www/ez_sql_postgresql.php on line 22

http://www.strabospot.org/validate/lDBN7YuFg3zKx7k2ADMLn

Warning: Require $dbuser and $dbpassword to connect to a database server in /var/www/ez_sql_postgresql.php on line 84

**Comment by jasonash** [comment]
OK, should be fixed.
