### ISSUE TITLE
projects

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#15]
@jasonash  Can we make the ability to create projects under a user and then say which spots belong in that project? For the app, we'd need a way to list all the projects associated with a user,  download all the spots in a project,  upload to a specific project and delete spots in a project. 

I'm not quite sure on the structure you would want for it.  Like could 1 spot be in multiple projects? If that is true, a project would really be like a label instead instead of a folder?

**Comment by jasonash** [comment]
@jessica-azgs Sure, we can definitely do this. I think that each spot should be able to be in multiple projects, so it would work like a label as you state above.

Can you provide me with some example JSON you might want to use to make this work? Would there just be a "project" attribute on the uploaded feature? Once I have the specifics, I can move forward with the new REST controller(s).

**Comment by jessica-azgs** [comment]
Can the database just keep track of which spots are in which projects, rather than the spots keeping track of what projects they belong to?

The app will just download and upload as projects instead of individual sots.

**Comment by zmichels** [comment]
Makes perfect sense to me.

**Comment by jasonash** [comment]
@jessica-azgs Yes, the database will keep track of which spots belong to which projects. My question is how is the database going to know which project the spots belong to? Right now, the spots are uploaded one at a time, so unless there is a "project name" attribute the database won't know where they belong. Do you have an idea of how you would like to upload multiple spots along with a corresponding project identifier?

**Comment by jasonash** [comment]
@jessica-azgs OK, after re-reading your initial post, I think I have a plan to make this work.
I will create REST controllers that do the following:
1. Create a project for the authenticated user with a given name.
2. List all projects for authenticated user.
3. Upload spot to given project.
4. Download all spots for given project.
5. Delete all spots for given project.

**Comment by jasonash** [comment]
I have created API controllers to accomplish all of the tasks mentioned above.

Please see the documentation at:

http://strabospot.org/api#projectFunctions

**Comment by jessica-azgs** [comment]
What we were calling projects are now called datasets. API is working.
