### ISSUE TITLE
add caption to Upload Image route

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-server#21]
In the "Upload Image" route (POST: http://strabospot.org/db/image), in addition to supplying the variables:

* feature_id
* image_file

Can we also add:

* caption

Users in the mobile app can optionally add a caption to their images.

**Comment by jasonash** [comment]
I have altered the http://strabospot.org/db/image controller to handle caption as well as feature_id and image_file. Also, I have altered the featureImages controller to return captions along with URIs for each image.

Please see the updated documentation at:

http://strabospot.org/api#imageFunctions

**Comment by jessica-azgs** [comment]
Incorporated into app with commit 43305d55d58f2dfc8e5052cd42f1641a0d59f937
