### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#22]
@jasonash Trying to get a list of all my datasets (on code that was working and I haven't changed) and I'm getting the following error:

`" Parse error: syntax error, unexpected T_ENCAPSED_AND_WHITESPACE, expecting ']' in /var/www/db/controllers/ImageController.php on line 444 "`

**Comment by jessica-azgs** [comment]
Created a new dataset and looks like it's working again. The server will give me a list of my datasets.
