### ISSUE TITLE
allow username/email case insensitivity in authentication

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-server#24]
If I **POST** to ```/userAuthenticate``` with this JSON payload:
```
{
   "email": "Kevin.wu@gmail.com",
   "password": "*****"
}
```
I get a login failure.

But if I post:
```
{
   "email": "kevin.wu@gmail.com",
   "password": "*****"
}
```
it works.

I think we should allow case *insensitivity* for username/email as part of the login process.  The issue is that some phones will try to capitalize the first letter due to autocorrect, causing authentication to fail.

I created a companion issue for the strabo-mobile app to address this issue too.  https://github.com/StraboSpot/strabo-mobile/issues/161

**Comment by jessica-azgs** [comment]
Fixed. See https://github.com/StraboSpot/strabo-mobile/issues/161
