### ISSUE TITLE
upload ids for images

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#25]
@jasonash I added some functionality for images and now need to use IDs with images (they weren't being used before). Is it possible to allow the server to upload ids? I am creating them the same way I create the ids for spots. I am also now using height, width and title as properties for images now. This is in addition to caption, feature_id and image_file which were there before.

Properties for images I now have are:
- feature_id
- image_file
- caption
- id
- height
- width
- title

**Comment by jasonash** [comment]
@jessica-azgs I have altered the image upload controller to allow for additional fields per your note above. I have added id, width, height, and title.
Details can be found here:

http://strabospot.org/api#imageFunctions

**Comment by jessica-azgs** [comment]
Thanks. Can you also add "annotated"? That's just a boolean as to whether
or not the image has been used a map for annotation.


Jessica Good
GIS Applications Developer
Arizona Geological Survey
http://www.azgs.az.gov/
jessica.good@azgs.az.gov

**Comment by jasonash** [comment]
I have added "annotated" to the list of image properties per your note above.
