### ISSUE TITLE
Number fields as strings

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#26]
@jasonash When I uploaded your example shapefile, StillwaterPoints.zip, I noticed that the values for the data in the strike, dip, trend and plunge field are returned to the app from the server as strings. The app is expecting numbers since the KoBo models we're using says those fields must be numbers. I can of course try to convert each string field that is supposed to be a number to a number field in the app but then we're going to end up strikes, dips, trends and plunges in the database that are stored as both text and numbers and it's a lot more work for the app to fix invalid field values. I'm sure there are other fields too that supposed to be numbers but those are just 4 of the most prominent fields. Is it possible for the database follow more closely what has been defined in the models?

**Comment by jasonash** [comment]
@jessica-azgs I have updated the shapefile parser to cast strike, dip, trend, plunge, and rake as numeric. Surely there are other fields that should also be cast as numeric, and I will change those too when I can. I am out of the office until next week. I should be able to pick up on those then.
