### ISSUE TITLE
include image information in spot schema

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-server#27]
When we download all the spots for a given dataset (example http://www.strabospot.org/db/datasetSpots/107502), the dataset doesn't tell us which spots have images associated with them.  This requires that we attempt to enumerate through **all** of the spots in an attempt to see if an image is available for each particular spot.  This becomes problematic when there are lots of spots in a dataset, like the StillwaterPoints example where there are ~1700 spots.  In this example, even though the initial download of the spots for the StillwaterPoints dataset is fairly quick, the app slows to a crawl when it builds up ~1700 XHR requests in an attempt to find images associated with each spot.

Is it possible to include image information as part of the spot schema?  In other words, for every spot, include an `images` key only if there are images associated with this spot.  The `images` value should be an array of images similar to the response payload in `http://strabospot.org/db/featureImages/xxxxx`

**Comment by jasonash** [comment]
@ginxwar I have added an "images" attribute to the GeoJSON properties per your request above.

Here is an example output:
```
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [100,0],
            [101,0],
            [105,5],
            [100,1],
            [100,0]
          ]
        ]
      },
      "properties": {
        "id": 74837662273843,
        "modified_timestamp": 143143653590,
        "date": "2015-06-03",
        "self": "http://strabospot.org/db/feature/1234",
        "foo": "bar",
        "name": "My Test Feature Polygon Name here",
        "images": [
          {
            "height": 500,
            "id": 196038,
            "annotated": true,
            "title": "Title Here",
            "width": 600,
            "self": "http://strabospot.org/db/image/196038",
            "caption": "my first caption"
          },
          {
            "height": 500,
            "id": 196039,
            "annotated": false,
            "title": "New Title Here",
            "width": 600,
            "self": "http://strabospot.org/db/image/196039",
            "caption": "My New Caption Here"
          }
        ]
      }
    }
```
