### ISSUE TITLE
Get Profile Image 

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#29]
@jasonash I used your form  at http://strabospot.org/profileimageupload to upload a profile image however when it directs me to http://strabospot.org/db/profileimage I get 

```
{
Error: "ID must be provided. "
}

**Comment by jasonash** [comment]
I am unable to duplicate the error. Have you tried visiting this link in a browser? It seems to work correctly for me.

**Comment by jessica-azgs** [comment]
Fixed by @jasonash
