### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#3]
@jasonash For now I just used a CORS proxy (http://www.corsproxy.com/) to get around this issue and that works fine for testing but not sure that we ultimately want to do it this way.

**Comment by jasonash** [comment]
I have enabled CORS on the server. Please try your request again.

Jason

**Comment by jessica-azgs** [comment]
Sent the same exact request as yesterday (which worked yesterday) except I took out the `www.corsproxy.com` and it no longer works (it doesn't work leaving in `www.corsproxy.com` like yesterday either). The request I sent yesterday was `http://www.corsproxy.com/strabospot.org/db/feature/246`. I shouldn't need the corsproxy.com any longer so tried `http://strabospot.org/db/feature/246` today. I didn't change anything else.

```
XMLHttpRequest cannot load http://strabospot.org/db/feature/246. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 401.

**Comment by jessica-azgs** [comment]
And don't know if it helps but this is the error I get when I send the same request as yesterday. It's slightly different than the one above.

```
XMLHttpRequest cannot load http://www.corsproxy.com/strabospot.org/db/feature/246. The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://localhost:8100' is therefore not allowed access.

**Comment by jasonash** [comment]
Jessica,

I apologize for the trouble. After poring over the Apache CORS docs 
again, I realized that simply allowing cross-origin requests wasn't 
enough in this case. Authorization data is not enabled by default, so I 
had to add a few more rules to get it to work.

I added the following rules to the Apache config:

Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, 
DELETE, PUT"
Header always set Access-Control-Max-Age "1000"
Header always set Access-Control-Allow-Headers "x-requested-with, 
Content-Type, origin, authorization, accept, client-security-token"

Here is an off-site test you can use if necessary:

http://ecp.iedadata.org/ajaxtest

Please try your test again and let me know if it is still not working.

Jason

**Comment by jessica-azgs** [comment]
Still not working @jasonash and I get failed when trying to use your test.

**Comment by jasonash** [comment]
OK, added rewrite rule for request method. Please try again.

**Comment by jessica-azgs** [comment]
Great. Worked now without the www.corsproxy.com. Thnaks!
