### ISSUE TITLE
Let User Change Profile Name?

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#30]
@jasonash Is it possible to let the user change their profile name from the app and upload it? I know now you say `Note: "name" parameter is not accepted, as this information is gathered from the credentials table` for `Update Profile` but would this be easy enough to change? Or is there some reason we wouldn't want a user to be able to change their name in the app?

**Comment by jasonash** [comment]
@jessica-azgs I will alter the profile controller to allow the user to change the name associated with credentials.

**Comment by jasonash** [comment]
OK, I have altered the profile controller to accept an optional "name" parameter which alters the "name" parameter returned by the GET function. If no "name" is POSTed, the GET function will return a "firstname lastname" from the credentials table.

Here is an example POST:
{
  "name": "John Smith",
  "mapbox_access_token": "lkajsdflkj",
  "foo": "bar",
  "test":"here"
}

**Comment by jessica-azgs** [comment]
Thanks!
