### ISSUE TITLE
Invalid Project but Get 200 OK

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#32]
@jasonash If I try to GET a project that doesn't exist I am getting a 200 OK for the response. In response.data I'm getting `Error: "Project 14573975145403 not found."` Do we really want a 200 OK response if the project doesn't exist? If we do that's fine, I can look at the response data to see if the 'Error' field is there. I was just assuming I'd get a status other than 200 so wanted to double check with you.

**Comment by jasonash** [comment]
@jessica-azgs Thanks for the heads-up. I have fixed the header on the not found response to a 404. This should work as the others do now.
