### ISSUE TITLE
XLS Output failure

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#33]
If I upload points that don't have a geometry and try to do an XLS output. I get an error in the XLS file. The contents of the XLS file are:

![capture](https://cloud.githubusercontent.com/assets/1493985/13760643/6ff426d0-e9f1-11e5-890f-08e7469e1ed9.PNG)

**Comment by jasonash** [comment]
GeoJSON requires that each object have a geometry:

http://geojson.org/geojson-spec.html

But you are trying to upload objects with no geometry?

**Comment by jessica-azgs** [comment]
Yes, I am uploading spots without geometries. This was always an option in the app, to create a Spot but not geolocate it/give it a geometry. I don't know how often someone would do this - maybe you don't know where the spot is but you want to record information about it. There may be other scenarios too, I don't know. I just filter out spots without geometries when I draw the map.

**Comment by jasonash** [comment]
OK. The error above is being thrown by the GeoJSON library I am using. I will see if I can find a workaround.

**Comment by jasonash** [comment]
I was able to omit geometries from the spreadsheet that don't appear in the JSON. This error should be fixed now.
