### ISSUE TITLE
Orientation Fields Modifications

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#34]
@jasonash I made some modifications to `spot.properties.` fields to improve consistency between objects.

```
orientation_data.[orientation].name -> orientation_data.[orientation].label
orientation_data.[orientation].orientation_type -> orientation_data.[orientation].type
orientation_data.[orientation].associated_orientation.[associated_orientation].name -> orientation_data.[orientation].associated_orientation.[associated_orientation].label
orientation_data.[orientation].associated_orientation.[associated_orientation].orientation_type -> orientation_data.[orientation].associated_orientation.[associated_orientation].type
```

I didn't do the changes below yet. Would you be able to replicate these changes server side so people don't lose data (though I know we're really not supposed to be concerned with that, just wondering if it's easy)? I have code in the app that copies over the `name` field to the `label` field and `orientation_type` field to `type` field so the above changes won't result in loss of data. The changes below are more significant though. Seems like using `orientations` and `associated_orientations` elements are a little cleaner than what we have now. That's the only reason to switch. No time crunch on making this change but we do need to do it at about the same time. What do you think?

```
orientation_data -> orientations
orientation_data.[orientation].associated_orientation -> orientations.[orientation].associated_orientations
```

**Comment by jasonash** [comment]
@jessica-azgs Sure, this should be fairly straight-forward. Can we wait a bit on the orientation_data.orientation -> orientations.associated_orientations changes? Like you said, we need to make this change at the same time and it will take me a while to make this work. 

I'll get the other changes made as soon as possible.
