### ISSUE TITLE
Losing Pixel Coordinates After Upload

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#35]
@jasonash If I upload a spot that is mapped on an image and thus has pixel coordinates it seems to upload fine but then if I look at the data on the server (like the Excel file) or download it back into the app the coordinates have switched to (I think maybe) whatever the last coordinates were that were not pixels.

Here is snap of the response when uploading to the server:
![upload](https://cloud.githubusercontent.com/assets/1493985/17444469/edf81b80-5af4-11e6-9bb6-bd64fd6f5b49.PNG)

If I go straightaway and open the Excel file from strabospot.org I see 
![strabospot](https://cloud.githubusercontent.com/assets/1493985/17444489/0df80094-5af5-11e6-8790-f3b1932f8232.PNG)

And of course if I download into the app I get the same incorrect coordinates that the Excel files shows.

This used to work fine and I haven't tested it in awhile so I'm not sure when this changed or what happened.

**Comment by jasonash** [comment]
@jessica-azgs OK, I think I have this fixed now. I added some functionality for the ESRI plugin that returns real-world coordinates for each feature, and it managed to bleed through to the datasetspots controller. Please give it a try again.

**Comment by jessica-azgs** [comment]
Yup, works. Thanks.
