### ISSUE TITLE
Rock Units Not Downloading

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#36]
@jasonash For FC19 when I upload a project the app successfully sends the rocks units to the server.
![ru](https://cloud.githubusercontent.com/assets/1493985/17565049/9acc17fa-5eea-11e6-8d3b-823c7450847a.PNG)

But when I download the project the rock units are not part of the response from the server. It looks like tags and tools aren't coming back either.
![rudl](https://cloud.githubusercontent.com/assets/1493985/17565073/bc8b0d60-5eea-11e6-8fab-09d68cf8a867.PNG)

Do you know what's going on here? Odd thing is I can do the same steps with a different project and all of those objects missing above come back from the server correctly.
![rudl2](https://cloud.githubusercontent.com/assets/1493985/17565205/49bbeff6-5eeb-11e6-89e8-8bfba26a3a4d.PNG)

**Comment by jasonash** [comment]
@jessica-azgs Can you send me the JSON you are trying to POST?

Jason

**Comment by jessica-azgs** [comment]
{"date":"2016-03-31T01:26:54.740Z","id":14593876147401,"other_features":["geomorhic","hydrologic","paleontological","igneous","metamorphic","sedimentological","other"],"tools":{"Strike":234,"Dip":23},"preferences":{"orientation":true,"_3dstructures":true,"images":true,"drop_down_to_finish_typing":true,"other_features":true,"samples":true,"spot_prefix":"TC","starting_number_for_spot":227,"tags":true,"inferences":true},"rock_units":[{"unit_label_abbreviation":"Pi","map_unit_name":"Pegmatite 1300 ma","rock_type":"igneous","notes":"Pink play rich coarse grained granite"},{"unit_label_abbreviation":"S2","map_unit_name":"Garnet schist"},{"unit_label_abbreviation":"Gb","map_unit_name":"Red plag rich granitic basement","notes":"Red plag rich granitic basement"},{"unit_label_abbreviation":"Q1","map_unit_name":"white quartzite","notes":"Grey white quartzite with minor amounts of schisty foliation","rock_type":"metamorphic","metamorphic_rock_types":"quartzite"},{"unit_label_abbreviation":"S1","notes":"Mica rich schist","map_unit_name":"Low grade mica schist","rock_type":"metamorphic","metamorphic_rock_types":"schist"},{"unit_label_abbreviation":"Q2","map_unit_name":"Dark blue-grey quartzite","description":"Quartzite with a dark blue-grey color. Predominantly Quartz however includes substantial amounts of magnetite biotite? And other mafic minerals. More massive than thenorthern quartzite.","absolute_age_of_geologic_unit":1500,"age_uncertainty":null,"rock_type":"metamorphic","metamorphic_rock_types":"quartzite"},{"unit_label_abbreviation":"Jm","map_unit_name":"Jurassic morrison","rock_type":"sedimentary","sedimentary_rock_type":"conglomerate","notes":"Red conglomeratic pebble to boulder. Corarse grained matrix. Crossbeds laminations, interlayered white limey? Lenses."},{"unit_label_abbreviation":"Jd","map_unit_name":"Jurassic dakota","rock_type":"sedimentary","sedimentary_rock_type":"sandstone","notes":"Orange yellow brown well sorted f-m sandstone with abundant sed structures. Xbeds xtriugh beds laminations. Red iron rich concretions are observed to weather out."},{"unit_label_abbreviation":"Jr","map_unit_name":"Upper Jurassic Ralsten","rock_type":"sedimentary","epoch":"other","other_epoch":"Jr","period":"jurassic","era":"mesozoic","notes":"Sand stone with red feldspar clasts.","sedimentary_rock_type":"sandstone"},{"unit_label_abbreviation":"Dh","map_unit_name":"Devonian harding","rock_type":"sedimentary","notes":"Quartz rich angular mm size clasts white cream grey and angular orthoclase clasts. Grain size is variable. Top is a yellow sandstone."},{"unit_label_abbreviation":"Pf","map_unit_name":"Pennsylvanian fountain","rock_type":"sedimentary","period":"jurassic","notes":"Red white conglomeratic unit."},{"unit_label_abbreviation":"Df","map_unit_name":"Devonian Freemont","rock_type":"sedimentary","epoch":"other","other_epoch":"Devonian","period":"devonian","notes":"White red limestone."}],"tags":[{"id":"14660353960839","name":"S1","categorization":"geological_unit","description":"Biotite muscovite rich schist with very few to no accessory minerals."},{"id":"14660355199166","name":"Q1","categorization":"geological_unit","description":"Massive quartzite"},{"id":"14660355622537","name":"S2","categorization":"geological_unit","description":"Schist with abundant psuedomorphs possibly retrograded garnets"},{"id":"14660356337516","name":"Gb","categorization":"geological_structure","description":"Red fine grained plagioclase rich granitic basement"},{"id":"14660356982538","name":"Pi","categorization":"geological_unit","description":"Coarse grained pegmatite intrusives weathers black and lumpy, often has moss on it. These are often very localized events."},{"id":"14660352420155","name":"Qal","categorization":"geological_unit","description":"Quaternary alluvium","spots":[14660351582818]},{"id":"14660360105747","spots":[14660238013955],"name":"Points","categorization":"other","other_categorization":"Photos randown inqueries"},{"id":"14660358701587","name":"Contacts","categorization":"other","other_categorization":"Geologic contact","spots":[14660340596188,14660339671809,14660339391065,14660337273443,14660336933551]}],"modified_timestamp":1470849365922,"description":{"project_name":"Field Camp 2016"}}

**Comment by jasonash** [comment]
Pretty JSON:
{
   "date":"2016-03-31T01:26:54.740Z",
   "id":14593876147401,
   "other_features":[
      "geomorhic",
      "hydrologic",
      "paleontological",
      "igneous",
      "metamorphic",
      "sedimentological",
      "other"
   ],
   "tools":{
      "Strike":234,
      "Dip":23
   },
   "preferences":{
      "orientation":true,
      "_3dstructures":true,
      "images":true,
      "drop_down_to_finish_typing":true,
      "other_features":true,
      "samples":true,
      "spot_prefix":"TC",
      "starting_number_for_spot":227,
      "tags":true,
      "inferences":true
   },
   "rock_units":[
      {
         "unit_label_abbreviation":"Pi",
         "map_unit_name":"Pegmatite 1300 ma",
         "rock_type":"igneous",
         "notes":"Pink play rich coarse grained granite"
      },
      {
         "unit_label_abbreviation":"S2",
         "map_unit_name":"Garnet schist"
      },
      {
         "unit_label_abbreviation":"Gb",
         "map_unit_name":"Red plag rich granitic basement",
         "notes":"Red plag rich granitic basement"
      },
      {
         "unit_label_abbreviation":"Q1",
         "map_unit_name":"white quartzite",
         "notes":"Grey white quartzite with minor amounts of schisty foliation",
         "rock_type":"metamorphic",
         "metamorphic_rock_types":"quartzite"
      },
      {
         "unit_label_abbreviation":"S1",
         "notes":"Mica rich schist",
         "map_unit_name":"Low grade mica schist",
         "rock_type":"metamorphic",
         "metamorphic_rock_types":"schist"
      },
      {
         "unit_label_abbreviation":"Q2",
         "map_unit_name":"Dark blue-grey quartzite",
         "description":"Quartzite with a dark blue-grey color. Predominantly Quartz however includes substantial amounts of magnetite biotite? And other mafic minerals. More massive than thenorthern quartzite.",
         "absolute_age_of_geologic_unit":1500,
         "age_uncertainty":null,
         "rock_type":"metamorphic",
         "metamorphic_rock_types":"quartzite"
      },
      {
         "unit_label_abbreviation":"Jm",
         "map_unit_name":"Jurassic morrison",
         "rock_type":"sedimentary",
         "sedimentary_rock_type":"conglomerate",
         "notes":"Red conglomeratic pebble to boulder. Corarse grained matrix. Crossbeds laminations, interlayered white limey? Lenses."
      },
      {
         "unit_label_abbreviation":"Jd",
         "map_unit_name":"Jurassic dakota",
         "rock_type":"sedimentary",
         "sedimentary_rock_type":"sandstone",
         "notes":"Orange yellow brown well sorted f-m sandstone with abundant sed structures. Xbeds xtriugh beds laminations. Red iron rich concretions are observed to weather out."
      },
      {
         "unit_label_abbreviation":"Jr",
         "map_unit_name":"Upper Jurassic Ralsten",
         "rock_type":"sedimentary",
         "epoch":"other",
         "other_epoch":"Jr",
         "period":"jurassic",
         "era":"mesozoic",
         "notes":"Sand stone with red feldspar clasts.",
         "sedimentary_rock_type":"sandstone"
      },
      {
         "unit_label_abbreviation":"Dh",
         "map_unit_name":"Devonian harding",
         "rock_type":"sedimentary",
         "notes":"Quartz rich angular mm size clasts white cream grey and angular orthoclase clasts. Grain size is variable. Top is a yellow sandstone."
      },
      {
         "unit_label_abbreviation":"Pf",
         "map_unit_name":"Pennsylvanian fountain",
         "rock_type":"sedimentary",
         "period":"jurassic",
         "notes":"Red white conglomeratic unit."
      },
      {
         "unit_label_abbreviation":"Df",
         "map_unit_name":"Devonian Freemont",
         "rock_type":"sedimentary",
         "epoch":"other",
         "other_epoch":"Devonian",
         "period":"devonian",
         "notes":"White red limestone."
      }
   ],
   "tags":[
      {
         "id":"14660353960839",
         "name":"S1",
         "categorization":"geological_unit",
         "description":"Biotite muscovite rich schist with very few to no accessory minerals."
      },
      {
         "id":"14660355199166",
         "name":"Q1",
         "categorization":"geological_unit",
         "description":"Massive quartzite"
      },
      {
         "id":"14660355622537",
         "name":"S2",
         "categorization":"geological_unit",
         "description":"Schist with abundant psuedomorphs possibly retrograded garnets"
      },
      {
         "id":"14660356337516",
         "name":"Gb",
         "categorization":"geological_structure",
         "description":"Red fine grained plagioclase rich granitic basement"
      },
      {
         "id":"14660356982538",
         "name":"Pi",
         "categorization":"geological_unit",
         "description":"Coarse grained pegmatite intrusives weathers black and lumpy, often has moss on it. These are often very localized events."
      },
      {
         "id":"14660352420155",
         "name":"Qal",
         "categorization":"geological_unit",
         "description":"Quaternary alluvium",
         "spots":[
            14660351582818
         ]
      },
      {
         "id":"14660360105747",
         "spots":[
            14660238013955
         ],
         "name":"Points",
         "categorization":"other",
         "other_categorization":"Photos randown inqueries"
      },
      {
         "id":"14660358701587",
         "name":"Contacts",
         "categorization":"other",
         "other_categorization":"Geologic contact",
         "spots":[
            14660340596188,
            14660339671809,
            14660339391065,
            14660337273443,
            14660336933551
         ]
      }
   ],
   "modified_timestamp":1470849365922,
   "description":{
      "project_name":"Field Camp 2016"
   }
}

**Comment by jasonash** [comment]
@jessica OK, I think I have this sorted out now. This is another bug that has come up from spotids not being unique. I have a feeling this is going to cause more trouble in the future.

I had to roll back the database to last night's backup, so anything you've added today will be gone.

Please try your upload/download again and let me know if you are still seeing the issue.

Jason

**Comment by jessica-azgs** [comment]
Ok, It's downloading fine now.

Which are the spots that have duplicate id? Were there some in this project you noticed?

**Comment by jasonash** [comment]
Sorry, I meant straboid (or id) For example there are 21 projects with the above id (14660360105747) 
![screenshot 2016-08-10 14 30 28](https://cloud.githubusercontent.com/assets/7904402/17568001/4ac358fa-5f07-11e6-8b10-851f9ddd47dd.png)

Doug used iMazing to make a copy of a project and uploaded it as 20 different users for field camp. 

This isn't a problem now, but once we start trying to add usergroups and collaboration options, this will have to be dealt with.

**Comment by jessica-azgs** [comment]
Ah, ok that makes more sense since it was a duplicate project.
