### ISSUE TITLE
Excel files not downloading correctly

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-server#37]
Excel files not downloading at strobspot.org for blue ridge and temple canyon in account fc7.

**Comment by jasonash** [comment]
@jessicagood and @egbunse I just downloaded all of the datasets from strabospot.org under account fc7 as spreadsheets and they seem to work fine for me. Can you guys try the downloads again and verify they aren't working? I'm using OSX, but I think you are both using Windows? I might have to re-work the excel output if the downloads aren't working on WinOffice installs. I'll attache the downloaded file to this message if you want to try that route too.
[XLSFiles.zip](https://github.com/StraboSpot/strabo-server/files/414245/XLSFiles.zip)

**Comment by jessicagood** [comment]
@jasonash I'm on Windows. Excel won't open the datasets blue ridge or temple canyon when downloaded from the site or from the zip you attached. twin mountain opens fine. Below is the error message. Clicking 'Yes' on the error message doesn't help either.
![capture](https://cloud.githubusercontent.com/assets/1493985/17605474/6f1f86ec-5fcf-11e6-9e57-b51b82726473.PNG)

**Comment by jasonash** [comment]
@jessicagood Thanks for the update. I'll work on migrating to a new XLS library.

**Comment by egbunse** [comment]
@jasonash I also got the same error as @jessicagood when trying to open the file from fc7 in Excel. Tried some of the datasets in my own account and all Strabo-created datasets throw that error, but a non-Strabo originating shapefile that I had been using to test the code you sent me in July to upload a zipped shapefile to StraboSpot downloaded fine.

**Comment by jasonash** [comment]
Thanks, @egbunse I'm going to migrate the export code to a new XLS library. It should be done by tomorrow morning.

**Comment by jasonash** [comment]
@jessica and @egbunse Can you try opening this file? I've created it with a new XLS library and I'm hoping it will work on Windows too. Thanks.
[Temple_Canyon_New_Library.zip](https://github.com/StraboSpot/strabo-server/files/414332/Temple_Canyon_New_Library.zip)

**Comment by jessicagood** [comment]
Getting the following error but it does open.
![capture](https://cloud.githubusercontent.com/assets/1493985/17606969/63a17e12-5fd7-11e6-8d6e-9b9128e7bb23.PNG)

**Comment by jasonash** [comment]
@jessicagood OK, I'll keep working on it.

**Comment by jasonash** [comment]
@jessicagood OK, I think it might have just been a file extension problem. Can you try this file and see if the error goes away? Thanks.
[Temple_Canyon_New_Library.zip](https://github.com/StraboSpot/strabo-server/files/414361/Temple_Canyon_New_Library.zip)

**Comment by jessicagood** [comment]
Yup, that worked without error.

**Comment by jasonash** [comment]
@jessicagood Great, I'll switch things over to that library.

**Comment by jasonash** [comment]
@egbunse Can you try downloading the spreadsheets from strabospot.org and see if they are working now? Jessica says that they are working fine for her now. Thanks.

**Comment by egbunse** [comment]
@jasonash Works perfectly for both the fc19 account and the few datasets I tried on my account.
