### ISSUE TITLE
ArcShapefiles Upload Not Working 

### ISSUE THREAD

**Issue by egbunse** [StraboSpot/strabo-server#39]
@jasonash , for some reason the page for uploading shapefiles isn't working. I have not changed the code you sent me. Here's what pops up when it directs from ArcMap to the browser: 
one tab with address: http://www.strabospot.org/loadarcshapefile?arcid=can%27t and error of: "Warning: ERROR: syntax error at or near "t" LINE 1: select count(*) from arcfiles where arcid='can't' ^ in /var/www/ez_sql_postgresql.php on line 203"
another tab with address: "open/" and another with address: "file/" 
I'm not sure if this is because of the new design to the app and database?

**Comment by jasonash** [comment]
Missing config file in new shapefile library. Fixed now.
