### ISSUE TITLE
Response when Creating Features

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#4]
@jasonash Looks like I am successfully posting features and I get a 201 but the response is 

`{"self":"http:\/\/strabospot.org\/db\/feature\/"}`

Any ideas?
 
This is what I'm sending

```
Remote Address:159.87.39.3:80
Request URL:http://strabospot.org/db/feature
Request Method:POST
Status Code:201 Created
Response Headers
view source
Access-Control-Allow-Headers:x-requested-with, Content-Type, origin, authorization, accept, client-security-token
Access-Control-Allow-Methods:POST, GET, OPTIONS, DELETE, PUT
Access-Control-Allow-Origin:*
Access-Control-Max-Age:1000
Connection:Keep-Alive
Content-Length:49
Content-Type:application/json; charset=utf8
Date:Mon, 12 Jan 2015 18:30:55 GMT
Keep-Alive:timeout=5, max=99
Server:Apache/2.2.22 (Ubuntu)
X-Powered-By:PHP/5.3.10-1ubuntu3.15
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Authorization:[AUTH HERE]
Connection:keep-alive
Content-Length:203
Content-Type:application/json;charset=UTF-8
Host:strabospot.org
Origin:http://localhost:8100
Referer:http://localhost:8100/
User-Agent:Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53
Request Payload
{"geometry":{"type":"Point","coordinates":[-104.43968125314736,45.1298667417031]},"type":"Feature","properties":{"date":"2014-12-10","time":"17:27","strike":2,"dip":0,"name":"rdfg","id":"1418257656430"}}
```

**Comment by jasonash** [comment]
The API is expecting a "spotType" but none in provided in your request 
below. Should I relax this requirement?

This JSON will work:

{
     "geometry":{
         "type":"Point",
         "coordinates":[-104.43968125314736,45.1298667417031]
     },
     "type":"Feature",
     "properties":{
         "spotType":"c",
         "date":"2014-12-10",
         "time":"17:27",
         "strike":2,
         "dip":0,
         "name":"rdfg",
         "id":"1418257656430"
     }
}

**Comment by jessica-azgs** [comment]
Yeah, maybe just require a name and id for now.

**Comment by jasonash** [comment]
OK, Please try original request.

**Comment by jasonash** [comment]
It looks like you are also trying to add information for strike/dip. 
These have not been added to the API yet, but I will add them now.

**Comment by jessica-azgs** [comment]
Oh ok. I guess I was figuring if the field didn't exist already it would be added automatically by the server side code. I have a bunch of other fields in the sample form too and we need to be able to give the user the ability to add their own key-value pairs. Guess we need to sync up on this a little more now.

**Comment by jasonash** [comment]
OK. Right now everything is static, but I will work to change the API to 
accept any key-value pairs. I should have this working tomorrow.

Jason

**Comment by jessica-azgs** [comment]
Now I get a 500

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.
```

**Comment by jasonash** [comment]
I just created a feature with no such error. Can you provide the JSON 
you are posting to get this error?

**Comment by jessica-azgs** [comment]
```
Remote Address:159.87.39.3:80
Request URL:http://strabospot.org/db/feature
Request Method:POST
Status Code:500 Internal Server Error
Response Headers
view source
Access-Control-Allow-Headers:x-requested-with, Content-Type, origin, authorization, accept, client-security-token
Access-Control-Allow-Methods:POST, GET, OPTIONS, DELETE, PUT
Access-Control-Allow-Origin:*
Access-Control-Max-Age:1000
Connection:close
Content-Encoding:gzip
Content-Length:398
Content-Type:text/html; charset=iso-8859-1
Date:Tue, 13 Jan 2015 23:21:34 GMT
Server:Apache/2.2.22 (Ubuntu)
Vary:Accept-Encoding
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Authorization:Basic undefined"
Connection:keep-alive
Content-Length:204
Content-Type:application/json;charset=UTF-8
Host:strabospot.org
Origin:http://localhost:8100
Referer:http://localhost:8100/
User-Agent:Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53
Request Payload
{"geometry":{"type":"Point","coordinates":[-85.71897812814736,42.271342448521665]},"type":"Feature","properties":{"date":"2014-12-10","time":"17:17","strike":0,"dip":0,"name":"aaaa","id":"1418257064590"}}
```

**Comment by jasonash** [comment]
This seems to work fine for me. Here is the created feature:

http://strabospot.org/db/feature/356

**Comment by jessica-azgs** [comment]
Yeah, right. I see. So it created the feature but returned a 500 anyway? Not sure. I'm headed home now. Can test it more tomorrow.

**Comment by jasonash** [comment]
No, I created the feature. I'm not sure what is causing the 500. I don't 
see that. Have you tried this request from a REST client other than the app?

**Comment by jessica-azgs** [comment]
Here is a it with a curl request. Not sure that I did the request correctly but not getting a 500, getting a 201 and some server errors.

```
developer@ubuntu-dev:~$ curl -D- -X POST -H "Authorization: Basic AUTH" -H "Content-Type: application/json" http://strabospot.org/db/feature {"geometry":{"type":"Point","coordinates":[-104.43968125314736,45.1298667417031]},"type":"Feature","properties":{"date":"2014-12-10","time":"17:27","strike":2,"dip":0,"name":"rdfg","id":"1418257656430"}}
HTTP/1.1 201 Created
Date: Wed, 14 Jan 2015 17:32:35 GMT
Server: Apache/2.2.22 (Ubuntu)
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT
Access-Control-Max-Age: 1000
Access-Control-Allow-Headers: x-requested-with, Content-Type, origin, authorization, accept, client-security-token
X-Powered-By: PHP/5.3.10-1ubuntu3.15
Content-Length: 271
Content-Type: application/json; charset=utf8


Warning: Invalid argument supplied for foreach() in /var/www/db/controllers/FeatureController.php on line 292

Warning: Invalid argument supplied for foreach() in /var/www/db/controllers/FeatureController.php on line 343
curl: (6) Couldn't resolve host 'geometry:type'
curl: (3) [globbing] illegal character in range specification at pos 23
curl: (3) [globbing] unmatched close brace/bracket at pos 26
curl: (6) Couldn't resolve host 'type'
curl: (6) Couldn't resolve host 'properties:date:2014-12-10'
curl: (6) Couldn't resolve host 'properties:time:17'
curl: (6) Couldn't resolve host 'properties:strike'
curl: (6) Couldn't resolve host 'properties:dip'
curl: (6) Couldn't resolve host 'properties:name'
curl: (3) Port number too large: 1418257656430
```

**Comment by jasonash** [comment]
Jessica,

The curl request you are sending is not well-formed.

First, you are not providing a base64 encoding of the auth 
(jessica.good@azgs.az.gov:strabotest) string. This malformed 
Authentication header is what is causing the 500 error.

Also, if you are wishing to send a POSTed body, it must be enclosed in 
quotes with a -d switch. Otherwise, your machine will interpret this 
JSON as several hosts, which caused the "Couldn't resolve" errors below.

This curl statement should work:

curl -X POST -H "Authorization: Basic 
amVzc2ljYS5nb29kQGF6Z3MuYXouZ292OnN0cmFib3Rlc3Q=" -H "Content-Type: 
application/json" http://strabospot.org/db/feature -d 
'{"geometry":{"type":"Point","coordinates":[-104.43968125314736,45.1298667417031]},"type":"Feature","properties":{"date":"2014-12-10","time":"17:27","strike":2,"dip":0,"name":"rdfg","id":"1418257656430"}}'

Jason

**Comment by jessica-azgs** [comment]
Fixed now. Thanks!

**Comment by jessica-azgs** [comment]
Now I'm getting a 201 but getting the error

`Warning: Invalid argument supplied for foreach() in /var/www/db/controllers/FeatureController.php on line 343
{"self":"http:\/\/strabospot.org\/db\/feature\/"}`

**Comment by jasonash** [comment]
Can you post the JSON you are sending?

**Comment by jessica-azgs** [comment]
Same as the first post ... not changing the JSON.

**Comment by jasonash** [comment]
There must be an error in your code. The following POST works as 
expected, right?

curl -X POST -H "Authorization: Basic AUTH_HERE" -H "Content-Type: 
application/json" http://strabospot.org/db/feature -d 
'{"geometry":{"type":"Point","coordinates":[-104.43968125314736,45.1298667417031]},"type":"Feature","properties":{"date":"2014-12-10","time":"17:27","strike":2,"dip":0,"name":"rdfg","id":"1418257656430"}}'

**Comment by jasonash** [comment]
I just looked at the error in the log. There is no body being send with 
your request.

Jason

**Comment by jessica-azgs** [comment]
Ok. So yes doing it with the curl request is working. However, it is creating a new feature, instead of doing an update, even if a feature already exists with the same id.

Trying to see why there is no body when sending from the app. The request payload is not empty but maybe that's different from the body.

**Comment by jasonash** [comment]
OK. Yes, I don't have the update functionality working yet. I will add 
this soon.

**Comment by jasonash** [comment]
OK, I just added some error detection for when the body isn't sent 
correctly. I hope this helps to debug.

**Comment by jessica-azgs** [comment]
Had to add another module to angular so now it is uploading a body and I get a 201 but in the response I'm getting the following and it's not actually creating the feature. 

```
Array
(
    [geometry] => Array
        (
            [type] => LineString
            [coordinates] => Array
                (
                    [0] => Array
                        (
                            [0] => -110.98175941370016
                            [1] => 32.22515319691583
                        )

                    [1] => Array
                        (
                            [0] => -110.9828322973061
                            [1] => 32.216621208943735
                        )

                    [2] => Array
                        (
                            [0] => -110.9842914190102
                            [1] => 32.21193735174211
                        )

                    [3] => Array
                        (
                            [0] => -110.9886258687783
                            [1] => 32.208015797385755
                        )

                    [4] => Array
                        (
                            [0] => -110.9891837682534
                            [1] => 32.20634545436896
                        )

                )

        )

    [type] => Feature
    [properties] => Array
        (
            [date] => 2014-12-09
            [time] => 09:45
            [name] => Santa Cruz River
            [strike] => 80
            [dip] => 60
            [attitude_type] => linear
            [id] => 1418143547215
        )

    [self] => http://strabospot.org/db/feature/
)
```

**Comment by jasonash** [comment]
You are sending the wrong Content-Type header.

You are sending:

Content-Type:"application/x-www-form-urlencoded",

but it should be:

Content-Type:"application/json"

**Comment by jessica-azgs** [comment]
Ah, that was it! Uploaded them and successfully download them with Get My Features
