### ISSUE TITLE
Duplicate Images

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#40]
@jasonash Like we talked about last week, I'm still getting images duplicates when downloading from the server even though duplicates were not sent to the server. Any luck fixing this or are you just holding off until the new backend is in place or busy working on something else?

**Comment by jasonash** [comment]
I tried multiple times to duplicate this issue, but I don't have an ipad to test with and I couldn't get duplicate images to upload. I have the new backend working solidly on a local machine, so I'm hoping that the issue will be fixed when we move things over.

**Comment by jessicagood** [comment]
This this is ok now
