### ISSUE TITLE
Getting a 202 for nonexistent dataset

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#41]
@jasonash Trying to request `http://strabospot.org/db/datasetSpots/14774290981362` which didn't exist on the server at the time of request but got a 200. The data was null though of course. Should it be a 200 if the dataset doesn't exist? If so I can deal with the response as you send it to me but I wanted to check.

**Comment by jasonash** [comment]
@jessicagood OK, try it again. You should be getting a 404 for an empty/missing dataset now.

**Comment by jessicagood** [comment]
Yup. Works now.
