### ISSUE TITLE
Upload/Download dataset with 0 Spots

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#42]
If you upload the properties for a dataset and then try to upload the Spots to `datasetSpots` the server gives an error if there are 0 Spots. 

If you try and download all spots for that dataset you get a `not found` error.  

How do I differentiate this error when trying to download from a dataset that exists but has 0 spots from trying to download all spots from a dataset that doesn't exist since it looks like they give the same error?

**Comment by jasonash** [comment]
@jessicagood The datasetSpots controller only deals with spots. If you want to check for the existence of a dataset, you should use the dataset controller, located here:

`http://strabospot.org/db/dataset/14725081181717`

The datasetSpots controller only looks at spots, and will return a 404 if no spots are found.

If you want me to change this behavior I can, but I'm not sure how else to differentiate the fact that a dataset has no spots and a dataset does not exist.
