### ISSUE TITLE
'Fatal Error' Thrown

### ISSUE THREAD

**Issue by egbunse** [StraboSpot/strabo-server#48]
Hi Jason, Logged in on the website to check some datasets I had added to my account with my Add-In and when I click 'Account' --> 'MyData' the website keeps giving me the following error: 
Fatal error: Uncaught GraphAware\Neo4j\Client\Exception\Neo4jException: Don't know how to compare that. Left: "1485980740804" (String); Right: 1485964426952 (Long) in /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php:122 Stack trace: #0 /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Client.php(64): GraphAware\Neo4j\Client\Connection\Connection->run('match (p:Projec...', Array, NULL) #1 /opt/www/ezneo4j.php(116): GraphAware\Neo4j\Client\Client->run('match (p:Projec...') #2 /opt/www/ezneo4j.php(123): ezneo4j->query('match (p:Projec...') #3 /opt/www/my_data.php(8): ezneo4j->get_results('match (p:Projec...') #4 {main} thrown in /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php on line 122

**Comment by jasonash** [comment]
Hi Emily,
It looks like you are casting "modified_timestamp" as a string when it should be cast as an integer. This was causing errors on a sort I added to the "my_data" page. I went ahead and fixed all of your projects manually, and added a conversion to the API. You might double-check that you're casting to integers.

**Comment by egbunse** [comment]
Hi Jason, Thanks for fixing those for me. I think I may have fixed the issue but want to check with you on the process: previously, modified timestamp was converted to String before it was added to the database, but this was because when I generate the json for creating a project or dataset I use StringBuilder. Before, when the json was created, all of the values would get quotes around them like this: "modified_timestamp" : "1486569099971", 
Now, when the json is created that line will look like this: "modified_timestamp" :  1486575223772,
Will this be enough or should I stop using StringBuilder to make my Json?

**Comment by jasonash** [comment]
Emily,

Right, in JSON notation, values wrapped in quotes are considered strings while values NOT in quotes are considered integers (or floats).

This would be the correct notation:

"modified_timestamp": 123456789

Jason

**Comment by egbunse** [comment]
Thanks for answering that for me! Glad it wasn't a huge fix. Everything is changed to make modified timestamp an integer now. I'll make sure ids are integers too.
