### ISSUE TITLE
Get Fields Not Separated by Geometry

### ISSUE THREAD

**Issue by egbunse** [StraboSpot/strabo-server#49]
Hi @jasonash , Was testing my Download code for the first time in awhile and noticed that the optional request for Getting Fields for a Dataset where you add /point, /line, or /polygon to the end of the URI doesn't work the way it used to. If you add an "s" (i.e. /points) it will return fields used by all geometries in the dataset but not just the ones specific to that geometry. Let me know if I need to change something (I went through and made sure all my URIs began with "https" when the server changed). Here's a screenshot of what I get on my REST controller: 
![image](https://cloud.githubusercontent.com/assets/13857984/22756872/4d2db770-ee0e-11e6-8a3c-db3285058676.png)

**Comment by jasonash** [comment]
@egbunse OK, try it now. I think it is sorted out.

**Comment by egbunse** [comment]
@jasonash Thank you so much! Its working fine now for all geometries.
