### ISSUE TITLE
Upload Spots Error

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#50]
@jasonash Trying to upload a new Spot to an existing dataset and I'm getting a 200 back but the response is the following and the new Spot I'm trying to upload is not at strabospot.org. I've only been able to recreate this problem with this particular project.

Response:
Fatal error: Uncaught GraphAware\Neo4j\Client\Exception\Neo4jException: Failed to invoke procedure `spatial.addNode`: Caused by: org.neo4j.graphdb.NotFoundException: NODE[22521] has no property with propertyKey="wkt". in /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php:122 Stack trace: #0 /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Client.php(64): GraphAware\Neo4j\Client\Connection\Connection->run('match (n) where...', Array, NULL) #1 /opt/www/ezneo4j.php(192): GraphAware\Neo4j\Client\Client->run('match (n) where...') #2 /opt/www/db/strabospotclass.php(642): ezneo4j->addNodeToSpatial(22521) #3 /opt/www/db/controllers/DatasetSpotsController.php(109): StraboSpot->insertSpot('{\n "userpkey...') #4 /opt/www/db/index.php(77): DatasetSpotsController->postAction(Object(Request)) #5 {main} thrown in /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php on line 122

I'm sending the following:
{"type":"FeatureCollection","features":[{"properties":{"date":"2016-03-22T00:32:10.000Z","name":"Hio6","time":"2016-03-22T00:32:10.000Z","id":14586067306728,"modified_timestamp":1458766067799,"self":"http://strabospot.org/db/feature/14586067306728"},"type":"Feature"},{"geometry":{"type":"Point","coordinates":[-110.979742,32.224092999999996]},"properties":{"orientation_data":[{"id":14876551400111,"dip":17,"feature_type":"foliation","label":"foliation149","type":"planar_orientation","strike":149}],"name":"x750","date":"2017-02-21T05:32:20.000Z","time":"2017-02-21T05:32:20.000Z","id":14876551400115,"modified_timestamp":1487655140014},"type":"Feature"}]}

to 

https://strabospot.org/db/datasetspots/14585987280095

**Comment by jasonash** [comment]
@jessicagood I found a small bug in the spot API that was trying to update the spatial engine with null geometry data. Please try your upload again.

**Comment by jessicagood** [comment]
Looks like it works now. Great.
