### ISSUE TITLE
Cannot Delete Certain Populated Datasets/Projects 

### ISSUE THREAD

**Issue by egbunse** [StraboSpot/strabo-server#53]
Hi @jasonash I was on the website trying to get rid of some duplicate datasets and projects from testing the add-in and ran into this error. I think the issue is that this latest dataset I was working with was originally on Katie's account (her Malpais Mesa stuff). I downloaded it into ArcMap using her account and then uploaded it to my account through the add-in. Other populated datasets and projects that are my original test data I can delete without error. Not sure if I need to add something with my code to make sure datasets aren't connected by relationships (this new dataset should be unique since it has a new ID, etc.)? 
Fatal error: Uncaught GraphAware\Neo4j\Client\Exception\Neo4jException: Cannot delete node<245251>, because it still has relationships. To delete this node, you must first delete its relationships. in /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php:122 Stack trace: #0 /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Client.php(64): GraphAware\Neo4j\Client\Connection\Connection->run('match (p:Projec...', Array, NULL) #1 /opt/www/ezneo4j.php(116): GraphAware\Neo4j\Client\Client->run('match (p:Projec...') #2 /opt/www/db/strabospotclass.php(2533): ezneo4j->query('match (p:Projec...') #3 /opt/www/delete_project.php(8): StraboSpot->deleteProject('14888147416134') #4 {main} thrown in /opt/www/classes/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php on line 122

**Comment by jasonash** [comment]
@egbunse ,

The problem is that you've assigned spots to multiple datasets and the spots cannot be removed on their own. This is why it is important to make sure that spot ids remain unique.

Here is what is happening in the database:
![screenshot 2017-03-08 11 30 56](https://cloud.githubusercontent.com/assets/7904402/23715650/ea7c7e40-03f2-11e7-8d7c-a8d2aa8caffe.png)

I'll see if I can delete them manually. This will take a while though.

**Comment by egbunse** [comment]
@jasonash Thanks, what do you advise that I do to avoid this in the future? I've uploaded the same dataset across multiple projects before and haven't run into this issue yet (for example, Doug's Devil's Playground dataset is in Legacy and other projects).

**Comment by jasonash** [comment]
@egbunse Have you tried deleting those? I suspect they will have the same issue. It is important to keep all ids unique.

**Comment by egbunse** [comment]
@jasonash Yes, I see the same issue which is strange since I'm confident I've deleted that dataset several times without error since its one of my best test datasets, but now I know to not put myself in that situation. Should I start changing all ID's when uploading back to Strabo? That seems to be the solution for having multiple copies of the same dataset (which is the idea if people download to Arc then upload that edited dataset back to their account to keep working on the app with the edits). I was under the impression that when I upload a dataset again, the only information that should change along with the edits is the modified timestamp of the spot.

**Comment by jasonash** [comment]
@egbunse If you download a project and dataset, the dataset should keep all of the original ids but should only go back to the originating project. The problem we face now is that you have uploaded duplicate spots to varying datasets and varying projects. These ids should never change. For example, in the diagram above, you have uploaded the dataset "points" with five different ids to three projects with different ids. All of these datasets now contain the same spot. I'll see if I can add a check to the API to prevent this from happening and throw an error when an attempt is made.

**Comment by jasonash** [comment]
@egbunse I've added checks to the API to ensure that duplicate spots don't get uploaded to the database. Also, I manually deleted project "14888147416134" from above. Let me know if you find other projects that need deleted, and I'll do those manually too.

**Comment by egbunse** [comment]
@jasonash Thanks for putting in the safeguards. Now I'm not sure what to do on the add-in when a user wants to upload their edited Strabo dataset. Their two options are to upload it to a new project or to an existing project of their choosing- both create a new dataset. From what you're telling me, in order to preserve a spot only existing in one dataset, I need to change all the IDs- essentially uploading the same data (some edited) in different spots that aren't linked to the originals. Or the other solution is to only allow users to update their existing datasets and upload only the edited spots to the original dataset (update feature). Do either of those make sense?

**Comment by jasonash** [comment]
@egbunse If you are wanting to create a new dataset, the ids MUST be different. The ids are the unique identifiers for the spots and are what the database and app use to distinguish spots from one another. I was under the impression that the add-in was going to work the same as the app; a user would download a dataset, alter it, add to it, and upload it back to the server. When this is done with the app, the dataset on the server is always overwritten and always belongs to the same project it was downloaded from. If you want to create a new dataset in a new project, new ids will have to be assigned to all spots, orientations, samples, etc...

**Comment by egbunse** [comment]
@jasonash Thanks, that all makes complete sense, I just hadn't been implementing it that way. I'll make those corrections. I'll add a way for the user to overwrite a dataset through update dataset and make it clear this is the preferred method. However, if "copies" are uploaded (new dataset created), all IDs will get changed.
