### ISSUE TITLE
losing Spot geometry

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#59]
@jasonash I'm testing uploading/downloading spots for strat sections. The upload seems to work fine and the response I get from the server looks good but when I go to download the spots which have coordinates for their geometry they are missing the geometry. For the spots where the geometry returns there a new field 'geometrytype' that shouldn't be there appearing under properties.

The image basemap spots use coordinates too so I'm not sure why we're loosing the coordinates. The server responses on upload and download are below. I'll try to do a little more troubleshooting after lunch to see if I can get you anything else helpful.

Server Response on Upload:
`{"type":"FeatureCollection","features":[{"properties":{"images":[{"width":380,"id":15125953817774,"title":"More Zoom of Outcrop at Bo's Cliff","height":285,"image_type":"geological_cs","annotated":false,"self":"https:\/\/strabospot.org\/db\/image\/15125953817774"},{"width":500,"id":15125953624786,"title":"Zoom of Outcrop at Bo's Cliff","height":375,"image_type":"geological_cs","annotated":false,"self":"https:\/\/strabospot.org\/db\/image\/15125953624786"},{"width":259,"id":15125953490283,"title":"Outcrop at Bo's Cliff","image_type":"photo","height":194,"annotated":false,"self":"https:\/\/strabospot.org\/db\/image\/15125953490283"}],"date":"2017-12-06T21:21:38.000Z","sed":{"strat_section":{"strat_section_id":15131436856383,"label":"Hohoho","column_profile":"mixed_clastic"}},"name":"Bo's Cliff","time":"2017-12-06T21:21:38.000Z","id":15125952984949,"geometrytype":"Point","modified_timestamp":1513620066359,"self":"https:\/\/strabospot.org\/db\/feature\/15125952984949"},"geometry":{"type":"Point","coordinates":[-110.88968088544,32.351655385174]},"type":"Feature"},{"geometry":{"type":"Polygon","coordinates":[[[0,0],[0,40],[10,40],[10,0]]]},"properties":{"strat_section_id":15131436856383,"surface_feature":{"surface_feature_type":"strat_interval"},"sed":{"lithologies":{"column_profile":"clastic","principal_grain_size_clastic":"clay","interval_thickness":2,"thickness_units":"m","bed_package_or_covered":"Package"}},"date":"2017-12-13T06:09:21.000Z","time":"2017-12-13T06:09:21.000Z","id":15131453616674,"name":"15131453616674","modified_timestamp":1513275724483,"self":"https:\/\/strabospot.org\/db\/feature\/15131453616674"},"type":"Feature"},{"geometry":{"type":"Polygon","coordinates":[[[0,40],[0,45],[50,45],[50,40]]]},"properties":{"strat_section_id":15131436856383,"surface_feature":{"surface_feature_type":"strat_interval"},"sed":{"lithologies":{"column_profile":"mixed_clastic","principal_grain_size_clastic":"sand_fine_lwr","interval_thickness":0.25,"thickness_units":"m","bed_package_or_covered":"Package"}},"date":"2017-12-14T18:38:03.000Z","time":"2017-12-14T18:38:03.000Z","id":15132766833925,"name":"15132766833925","modified_timestamp":1513290342552,"self":"https:\/\/strabospot.org\/db\/feature\/15132766833925"},"type":"Feature"},{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-110.9002,32.3622],[-110.8932,32.362],[-110.8934,32.3564],[-110.8985,32.3549],[-110.9014,32.3552],[-110.9002,32.3622]]]},"properties":{"date":"2017-12-14T21:46:22.000Z","time":"2017-12-14T21:46:22.000Z","id":15132879826180,"name":"15132879826180","modified_timestamp":1513287982621,"wkt":"POLYGON ((-110.9002 32.3622, -110.8932 32.362, -110.8934 32.3564, -110.8985 32.3549, -110.9014 32.3552, -110.9002 32.3622))","origwkt":"POLYGON ((-110.9002 32.3622, -110.8932 32.362, -110.8934 32.3564, -110.8985 32.3549, -110.9014 32.3552, -110.9002 32.3622))","self":"https:\/\/strabospot.org\/db\/feature\/15132879826180"}},{"geometry":{"type":"Polygon","coordinates":[[[0,45],[0,60.2],[110,60.2],[110,45]]]},"properties":{"strat_section_id":15131436856383,"surface_feature":{"surface_feature_type":"strat_interval"},"sed":{"lithologies":{"column_profile":"clastic","principal_grain_size_clastic":"sand_v_coar","interval_thickness":0.76,"thickness_units":"m","bed_package_or_covered":"Package"}},"date":"2017-12-14T22:14:28.000Z","time":"2017-12-14T22:14:28.000Z","id":15132896681167,"name":"15132896681167","modified_timestamp":1513290300659,"self":"https:\/\/strabospot.org\/db\/feature\/15132896681167"},"type":"Feature"},{"geometry":{"type":"Polygon","coordinates":[[[0,60.2],[0,80.2],[140,80.2],[140,60.2]]]},"properties":{"strat_section_id":15131436856383,"surface_feature":{"surface_feature_type":"strat_interval"},"sed":{"lithologies":{"bed_package_or_covered":"Package","column_profile":"clastic","principal_grain_size_clastic":"cobble","interval_thickness":1,"thickness_units":"m"}},"date":"2017-12-14T22:26:30.000Z","time":"2017-12-14T22:26:30.000Z","id":15132903907212,"name":"15132903907212","modified_timestamp":1513290390722,"self":"https:\/\/strabospot.org\/db\/feature\/15132903907212"},"type":"Feature"},{"geometry":{"type":"Polygon","coordinates":[[[0,80.2],[0,100.2],[35,100.2],[35,80.2]]]},"properties":{"strat_section_id":15131436856383,"surface_feature":{"surface_feature_type":"strat_interval"},"sed":{"lithologies":{"column_profile":"carbonate","principal_dunham_classificatio":"packstone","interval_thickness":1,"thickness_units":"m"}},"date":"2017-12-14T22:51:45.000Z","time":"2017-12-14T22:51:45.000Z","id":15132919053391,"name":"15132919053391","modified_timestamp":1513291905341,"self":"https:\/\/strabospot.org\/db\/feature\/15132919053391"},"type":"Feature"},{"geometry":{"type":"Polygon","coordinates":[[[0,100.2],[0,112.2],[10,112.2],[10,100.2]]]},"properties":{"strat_section_id":15131436856383,"surface_feature":{"surface_feature_type":"strat_interval"},"sed":{"lithologies":{"interval_type":"misc_lithologi","misc_lithologies":"coal","interval_thickness":0.6,"thickness_units":"m"}},"date":"2017-12-18T16:40:10.000Z","time":"2017-12-18T16:40:10.000Z","id":15136152101179,"name":"15136152101179","modified_timestamp":1513615210119,"self":"https:\/\/strabospot.org\/db\/feature\/15136152101179"},"type":"Feature"},{"geometry":{"type":"Polygon","coordinates":[[[0,112.2],[0,152.2],[null,152.2],[null,112.2]]]},"properties":{"strat_section_id":15131436856383,"surface_feature":{"surface_feature_type":"strat_interval"},"sed":{"lithologies":{"interval_type":"weathering_pro","interval_thickness":2,"thickness_units":"cm"}},"date":"2017-12-18T16:49:11.000Z","time":"2017-12-18T16:49:11.000Z","id":15136157515113,"name":"15136157515113","modified_timestamp":1513615751513,"self":"https:\/\/strabospot.org\/db\/feature\/15136157515113"},"type":"Feature"}]}`

Server Response on Download:
`{"type":"FeatureCollection","features":[{"properties":{"date":"2017-12-14T18:38:03.000Z","sed":{"lithologies":{"column_profile":"mixed_clastic","principal_grain_size_clastic":"sand_fine_lwr","interval_thickness":0.25,"thickness_units":"m","bed_package_or_covered":"Package"}},"name":"15132766833925","strat_section_id":15131436856383,"time":"2017-12-14T18:38:03.000Z","surface_feature":{"surface_feature_type":"strat_interval"},"id":15132766833925,"modified_timestamp":1513290342552,"self":"https:\/\/strabospot.org\/db\/feature\/15132766833925"},"type":"Feature"},{"properties":{"date":"2017-12-13T06:09:21.000Z","sed":{"lithologies":{"column_profile":"clastic","principal_grain_size_clastic":"clay","interval_thickness":2,"thickness_units":"m","bed_package_or_covered":"Package"}},"name":"15131453616674","strat_section_id":15131436856383,"time":"2017-12-13T06:09:21.000Z","surface_feature":{"surface_feature_type":"strat_interval"},"id":15131453616674,"modified_timestamp":1513275724483,"self":"https:\/\/strabospot.org\/db\/feature\/15131453616674"},"type":"Feature"},{"properties":{"date":"2017-12-14T22:14:28.000Z","sed":{"lithologies":{"column_profile":"clastic","principal_grain_size_clastic":"sand_v_coar","interval_thickness":0.76,"thickness_units":"m","bed_package_or_covered":"Package"}},"name":"15132896681167","strat_section_id":15131436856383,"time":"2017-12-14T22:14:28.000Z","surface_feature":{"surface_feature_type":"strat_interval"},"id":15132896681167,"modified_timestamp":1513290300659,"self":"https:\/\/strabospot.org\/db\/feature\/15132896681167"},"type":"Feature"},{"properties":{"date":"2017-12-18T16:40:10.000Z","sed":{"lithologies":{"interval_type":"misc_lithologi","misc_lithologies":"coal","interval_thickness":0.6,"thickness_units":"m"}},"name":"15136152101179","strat_section_id":15131436856383,"time":"2017-12-18T16:40:10.000Z","surface_feature":{"surface_feature_type":"strat_interval"},"id":15136152101179,"modified_timestamp":1513615210119,"self":"https:\/\/strabospot.org\/db\/feature\/15136152101179"},"type":"Feature"},{"geometry":{"type":"Polygon","coordinates":[[[-110.9002,32.3622],[-110.8932,32.362],[-110.8934,32.3564],[-110.8985,32.3549],[-110.9014,32.3552],[-110.9002,32.3622]]]},"properties":{"date":"2017-12-14T21:46:22.000Z","name":"15132879826180","time":"2017-12-14T21:46:22.000Z","id":15132879826180,"geometrytype":"Polygon","modified_timestamp":1513287982621,"self":"https:\/\/strabospot.org\/db\/feature\/15132879826180"},"type":"Feature"},{"properties":{"date":"2017-12-14T22:51:45.000Z","sed":{"lithologies":{"column_profile":"carbonate","principal_dunham_classificatio":"packstone","interval_thickness":1,"thickness_units":"m"}},"name":"15132919053391","strat_section_id":15131436856383,"time":"2017-12-14T22:51:45.000Z","surface_feature":{"surface_feature_type":"strat_interval"},"id":15132919053391,"modified_timestamp":1513291905341,"self":"https:\/\/strabospot.org\/db\/feature\/15132919053391"},"type":"Feature"},{"properties":{"images":[{"width":380,"id":15125953817774,"title":"More Zoom of Outcrop at Bo's Cliff","height":285,"image_type":"geological_cs","annotated":false,"self":"https:\/\/strabospot.org\/db\/image\/15125953817774"},{"width":500,"id":15125953624786,"title":"Zoom of Outcrop at Bo's Cliff","height":375,"image_type":"geological_cs","annotated":false,"self":"https:\/\/strabospot.org\/db\/image\/15125953624786"},{"width":259,"id":15125953490283,"title":"Outcrop at Bo's Cliff","image_type":"photo","height":194,"annotated":false,"self":"https:\/\/strabospot.org\/db\/image\/15125953490283"}],"date":"2017-12-06T21:21:38.000Z","sed":{"strat_section":{"strat_section_id":15131436856383,"label":"Hohoho","column_profile":"mixed_clastic"}},"name":"Bo's Cliff","time":"2017-12-06T21:21:38.000Z","id":15125952984949,"geometrytype":"Point","modified_timestamp":1513620066359,"self":"https:\/\/strabospot.org\/db\/feature\/15125952984949"},"geometry":{"type":"Point","coordinates":[-110.88968088544,32.351655385174]},"type":"Feature"},{"properties":{"date":"2017-12-14T22:26:30.000Z","sed":{"lithologies":{"bed_package_or_covered":"Package","column_profile":"clastic","principal_grain_size_clastic":"cobble","interval_thickness":1,"thickness_units":"m"}},"name":"15132903907212","strat_section_id":15131436856383,"time":"2017-12-14T22:26:30.000Z","surface_feature":{"surface_feature_type":"strat_interval"},"id":15132903907212,"modified_timestamp":1513290390722,"self":"https:\/\/strabospot.org\/db\/feature\/15132903907212"},"type":"Feature"},{"properties":{"date":"2017-12-18T16:49:11.000Z","sed":{"lithologies":{"interval_type":"weathering_pro","interval_thickness":2,"thickness_units":"cm"}},"name":"15136157515113","strat_section_id":15131436856383,"time":"2017-12-18T16:49:11.000Z","surface_feature":{"surface_feature_type":"strat_interval"},"id":15136157515113,"modified_timestamp":1513615751513,"self":"https:\/\/strabospot.org\/db\/feature\/15136157515113"},"type":"Feature"}]}`

**Comment by jasonash** [comment]
@jessicagood Most of the geometries you are sending above are invalid. For example,

      {
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     0,
                     80.2
                  ],
                  [
                     0,
                     100.2
                  ],
                  [
                     35,
                     100.2
                  ],
                  [
                     35,
                     80.2
                  ]
               ]
            ]
         }

Is not valid. Polygon notation requires that the first and last vertices are identical, and therefore create a closed set. The correct version of the polygon above would be:

      {
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     0,
                     80.2
                  ],
                  [
                     0,
                     100.2
                  ],
                  [
                     35,
                     100.2
                  ],
                  [
                     35,
                     80.2
                  ],
                  [
                     0,
                     80.2
                  ]
               ]
            ]
         }

I will work on adding more robust checks to the api that would cause the request to error out instead of completing.

Jason

**Comment by jessicagood** [comment]
Ok, I fixed that and now it's working. Thanks. Openlayers was drawing the poly correctly without the last coordinate so I didn't think anything of it.

Do you know where that 'geometrytype' property under 'properties' is coming from?

**Comment by jasonash** [comment]
I think geometrytype was left over from an older version of the data model. I've removed it now.
