### ISSUE TITLE
name now featurename?

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#6]
@jasonash Did you change the property name to featurename? I need to go through and change a bunch of stuff if that's what we're using.

**Comment by jasonash** [comment]
I can change it back. I altered the API to allow any properties. Give me 
a few minutes.

**Comment by jessica-azgs** [comment]
Oh ok. name and id were the two that I had as required so that's why it messed me up a bit

**Comment by jasonash** [comment]
OK, it is fixed now. Sorry for the trouble.

**Comment by jessica-azgs** [comment]
Thanks!
