### ISSUE TITLE
self field

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#7]
@jasonash I think the self field needs to be in the list of properties to keep the geojson properly formed.

**Comment by jasonash** [comment]
OK, I'll change this in the morning.

**Comment by jasonash** [comment]
"self" field has been moved to properties.

**Comment by jessica-azgs** [comment]
@jasonash In some of the API documentation this is still not listed as in properties.

**Comment by jasonash** [comment]
OK, should be fixed.
