### ISSUE TITLE
server decides if spot is new or to be updated?

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#9]
@jasonash Is it possible to just send a spot to the server with `POST: http://strabospot.org/db/feature` and the server-side code decides if it should make a new spot or update an existing one? That would make the client-side code cleaner.

**Comment by jasonash** [comment]
That should be possible. This isn't exactly a RESTful approach, but I'll 
see what I can do. So you are assuming that there is a pre-existing 
feature with the same id then?

Jason

**Comment by jessica-azgs** [comment]
If it's not RESTful maybe that is not the correct approach. The server-side code would have to do the legwork to see if spot.properties,self is valid and then update and if not create a new feature. Just an idea.

**Comment by jasonash** [comment]
We can definitely do it your way if it helps out. I think we should 
maintain the other approach in the API to maintain compatibility with 
others.

**Comment by jasonash** [comment]
API code has been changed to accept POST as mentioned below. Now, if an 
"id" is provided, the server first checks for the existence of that 
feature. If it exists, it is updated. If it does not exist, a new 
feature is created and a new id and "self" is returned.
